#include "gat_define.h"

WEIGHT_TYPE target_attention_weights[NETWORK_LAYER_NUM][ATTENTION_HEAD_NUM][EMBEDDING_DIM];
WEIGHT_TYPE source_attention_weights[NETWORK_LAYER_NUM][ATTENTION_HEAD_NUM][EMBEDDING_DIM];
WEIGHT_TYPE linear_projection_weights[NETWORK_LAYER_NUM][ATTENTION_HEAD_NUM][EMBEDDING_DIM][ATTENTION_HEAD_NUM][EMBEDDING_DIM];
WEIGHT_TYPE skip_projection_weights[NETWORK_LAYER_NUM][ATTENTION_HEAD_NUM][EMBEDDING_DIM][ATTENTION_HEAD_NUM][EMBEDDING_DIM];
WEIGHT_TYPE graph_prediction_weights[TASK_NUM][EMBEDDING_DIM];
WEIGHT_TYPE graph_prediction_bias[TASK_NUM];

int node_degree_table[MAX_NODE_COUNT];
int parallel_degree_tables[EDGE_PARALLEL_FACTOR][MAX_NODE_COUNT];
int parallel_neighbor_tables[EDGE_PARALLEL_FACTOR][MAX_EDGE_COUNT];
int parallel_neighbor_tables2[EDGE_PARALLEL_FACTOR][MAX_EDGE_COUNT];
int edge_count_per_pe[EDGE_PARALLEL_FACTOR];

// BRAM for intermediate storage
FEATURE_MAP_VECTOR node_embedding_ping_buffer[EDGE_PARALLEL_FACTOR][ceildiv(MAX_NODE_COUNT, EDGE_PARALLEL_FACTOR)][EMBEDDING_DIM];
FEATURE_MAP_VECTOR node_embedding_pong_buffer[EDGE_PARALLEL_FACTOR][ceildiv(MAX_NODE_COUNT, EDGE_PARALLEL_FACTOR)][EMBEDDING_DIM];
FEATURE_MAP_VECTOR node_feature_skip_concat_bias_ping[MAX_NODE_COUNT][EMBEDDING_DIM];
FEATURE_MAP_VECTOR node_feature_skip_concat_bias_pong[MAX_NODE_COUNT][EMBEDDING_DIM];
FEATURE_MAP_VECTOR source_attention_scores_ping[EDGE_PARALLEL_FACTOR][MAX_NODE_COUNT];
FEATURE_MAP_VECTOR source_attention_scores_pong[EDGE_PARALLEL_FACTOR][MAX_NODE_COUNT];
FEATURE_MAP_VECTOR target_attention_scores_ping[EDGE_PARALLEL_FACTOR][ceildiv(MAX_NODE_COUNT, EDGE_PARALLEL_FACTOR)];
FEATURE_MAP_VECTOR target_attention_scores_pong[EDGE_PARALLEL_FACTOR][ceildiv(MAX_NODE_COUNT, EDGE_PARALLEL_FACTOR)];